/*
 * @Author: zhangenwei
 * @Date: 2024-02-19 10:16:15
 * @LastEditors: zhangenwei
 * @LastEditTime: 2024-02-19 10:16:15
 * @Description:
 */
#ifndef AIROS_MIDDLEWARE_PROTOCOL_RSAP_COMPONENT_DATAMODEL_NAMESPACE
#define AIROS_MIDDLEWARE_PROTOCOL_RSAP_COMPONENT_DATAMODEL_NAMESPACE

#define NAMESPACE_OS_START        namespace os {
#define NAMESPACE_OS_END          }

#define NAMESPACE_V2X_BASE_START   NAMESPACE_OS_START namespace v2x {
#define NAMESPACE_V2X_BASE_END     } NAMESPACE_OS_END

#define NAMESPACE_PROTOCOL_THREAD_START NAMESPACE_V2X_BASE_START namespace protocol {
#define NAMESPACE_PROTOCOL_THREAD_END   } NAMESPACE_V2X_BASE_END

#define LOG_KEY_RASP "[rsap]"
#define RSAP_DEBUG_PRINT LOG_INFO << LOG_KEY_RASP
#define RSAP_WARN_PRINT LOG_WARN << LOG_KEY_RASP
#define RSAP_ERROR_PRINT LOG_ERROR << LOG_KEY_RASP
#define RSAP_SUCCESS_PRINT LOG_INFO << LOG_KEY_RASP
#define RSAP_FATAL_PRINT   LOG_FATAL << LOG_KEY_RASP
#endif

