#! /usr/bin/bash


ips=`grep 'ip' /home/caros/cybertron/ip.yaml | awk '{print $2}'`

while true ;
do
    for ip in $ips
    do

        ping  $ip -w 2 -i 1 -s 800 -c 2 | grep 'packets' | awk -F"[ %]"  '{if($6 > 0) {print 1} else {print 0;}}' | xargs echo $(date  +"%Y-%m-%d %H:%M:%S") $ip >> net_status

    done 

done
