#!/usr/bin/env bash
set -e

# log_file=/home/airos/log/airos_launch.log."$(date +%Y%m%d-%H%M%S)"
GLOBAL_KILL_DAG_NAME=""
return_info() {
  local DATE_N=$(date "+%Y-%m-%d %H:%M:%S")
  [[ $# -eq 0 ]] && return
  echo -e "\033[1;32m [INFO]--- ${DATE_N} $* \033[0m"
}

function check_run() {
  local command_line="$1"
  if [[ -n ${command_line} ]]; then
    launch_cmd="${command_line} > /dev/null 2>&1 &"
    eval ${launch_cmd}
    return_info "${launch_cmd} , run successfully! "
  fi
}

function start_camera_viz() {
    mainboard -d dag/perception_camera_123_viz.dag
}

function start_fusion_viz() {
    mainboard -d dag/msf_component_viz.dag
}

function start_perception_pipeline() {
    check_run "mainboard -d dag/perception_camera_123.dag"
    check_run "mainboard -d dag/msf_component.dag"
}

function start_perception_lidar() {
    check_run "mainboard -d dag/perception_lidar_12.dag"
}

function start_traffic_light_pipeline() {
    check_run "mainboard -d dag/traffic_light_service.dag"
    check_run "mainboard -d dag/v2x_codec.dag"
    check_run "mainboard -d dag/rsu_service.dag"
    check_run "./bin/airos_app_framework conf/airos_v2x_app.pb"
}

function start_mec_pipeline() {
    check_run "mainboard -d dag/mec_service.dag"
    check_run "mainboard -d dag/v2x_codec.dag"
    check_run "mainboard -d dag/rsu_service.dag"
    check_run "./bin/airos_app_framework conf/airos_v2x_app.pb"
}
function start_rsap_pipeline() {
    check_run "mainboard -d dag/mec_service.dag"
    check_run "mainboard -d dag/rsap.dag"
}

function start_om_mec_ptp_pipeline() {
    local enable_front_flag="${1:-default_value1}"  # µÚÒ»¸ö²ÎÊý£¬Ä¬ÈÏÎª default_value1
    if [[ ${enable_front_flag} == "true" ]]; then
        start_kill_dag_pipeline
        check_run_front "python3 /home/airos/protocol/om/PTPpartlog.py /home/airos/common_config/work_param_config.flag"
    else
        check_run "python3 /home/airos/protocol/om/PTPpartlog.py /home/airos/common_config/work_param_config.flag"
    fi
}

function start_om_monitor_pipeline() {
    local enable_front_flag="${1:-default_value1}"  # µÚÒ»¸ö²ÎÊý£¬Ä¬ÈÏÎª default_value1
    if [[ ${enable_front_flag} == "true" ]]; then
        start_kill_dag_pipeline
        check_run_front "mainboard -d dag/om_monitor.dag"
    else
        check_run "mainboard -d dag/om_monitor.dag"
    fi

}

function start_om_device_status_pipeline() {
    local enable_front_flag="${1:-default_value1}" 
    if [[ ${enable_front_flag} == "true" ]]; then
      start_kill_dag_pipeline
      check_run_front "mainboard -d dag/om_device_status.dag"
    else
      check_run "mainboard -d dag/om_device_status.dag"
    fi
}
function start_om_pipeline() {
    local enable_front_flag="${1:-default_value1}"
    if [[ ${enable_front_flag} == "true" ]]; then
       echo "start om"
      start_kill_dag_pipeline
      echo "start om"
      check_run "python3 /home/airos/protocol/om/PTPpartlog.py /home/airos/common_config/work_param_config.flag"
      check_run "python3 /home/airos/protocol/om/PTPmonitor.py"
      check_run "mainboard -d dag/om_device_status.dag"
      check_run_front "mainboard -d dag/om.dag"
    else
      check_run "python3 /home/airos/protocol/om/PTPpartlog.py /home/airos/common_config/work_param_config.flag"
      check_run "python3 /home/airos/protocol/om/PTPmonitor.py"
      check_run "mainboard -d dag/om_device_status.dag"
      check_run "mainboard -d dag/om.dag"
    fi
}


function start_ccindex_pipeline() {
    local enable_front_flag="${1:-default_value1}"
    if [[ ${enable_front_flag} == "true" ]]; then
      start_kill_dag_pipeline
      check_run_front "mainboard -d dag/ccindex.dag"
    else
      check_run "mainboard -d dag/ccindex.dag"
    fi
}


function start_kill_dag_pipeline() {
  start_ps
  local target_pid=$(pgrep -f $GLOBAL_KILL_DAG_NAME)
   if [ -n "$target_pid" ]; then
      kill -9 $target_pid
   fi
}

function start_all() {
    check_run "mainboard -d dag/mec_service.dag"
    check_run "mainboard -d dag/traffic_light_service.dag"
    check_run "mainboard -d dag/v2x_codec.dag"
    check_run "mainboard -d dag/rsu_service.dag"
    check_run "mainboard -d dag/rsap.dag"
    # check_run "mainboard -d dag/perception_camera_123.dag"
    # check_run "mainboard -d dag/msf_component.dag"
    check_run "./bin/airos_app_framework conf/airos_v2x_app.pb"
    check_run "./bin/airos_app_framework conf/airos_v2x_scenario.pb"
    check_run "mainboard -d dag/om_device_status.dag"
    check_run "/home/airos/script/airos_keep_alive.sh"
    check_run "mainboard -d dag/ccindex.dag"
    check_run "mainboard -d dag/om.dag"
    check_run "mainboard -d dag/om_monitor.dag"
    check_run "python3 /home/airos/protocol/om/PTPpartlog.py /home/airos/common_config/work_param_config.flag"
    check_run "python3 /home/airos/protocol/om/PTPmonitor.py"
    echo '--------------'
    ps -ef | grep main
    echo '--------------'
    ps -ef | grep DianYunRecorder
    echo '--------------'
    ps -ef | grep PTPpartlog
    echo '--------------'
    ps -ef | grep PTPmonitor
    echo '--------------'
    ps -ef | grep airos_keep_alive
    echo '--------------'
}
function start_ps() {
    ps -ef | grep main
    echo '--------------'
    ps -ef | grep DianYunRecorder
    echo '--------------'
    ps -ef | grep PTPpartlog
    echo '--------------'
    ps -ef | grep PTPmonitor
    echo '--------------'
    ps -ef | grep airos_keep_alive
    echo '--------------'
    ps -ef | grep ./bin/airos_app_framework
    echo '--------------'
}

function stop_all() {
    pkill -f mainboard || true
    pkill -f airos_app_framework || true
    pkill -f airos_keep_alive || true
    pkill -f DianYunRecorder || true
    pkill -f PTPpartlog || true
    pkill -f PTPmonitor || true
    pkill -9 -f airos_app_framework || true
}

function print_usage() {
  echo "Usage: airos_launch [OPTIONS]"
  echo "Description: This is a tool script for launch airos pipeline."
  echo
  echo "Options:"
  echo "  -h                      Display this help message."
  echo "  camera_viz              Start perception camera viz."
  echo "  fusion_viz              Start fusion viz."
  echo "  perception              Start perception pipeline."
  echo "  traffic_light           Start traffic light pipeline."
  echo "  lidar                   Start lidar perception."
  echo "  mec                     Start [public]mec pipeline."
  echo "  rsap                    Start protocol-1 pipeline."
  echo "  om                      Start protocol-5 [om]OM pipeline."
  echo "  om_device_status        Start [pulibc]device status into seqlite3 pipeline."
  echo "  radar_cloud_point       Start radar cloud point pipeline."
  echo "  ccindex                 Start ddindex pipeline."
  echo "  kill                    Start kill dag pipeline."
  echo "  ps                      Check the status of pipelines."
  echo "  all                     Start airos all pipeline."
  echo "  stop                    Stop all pipeline."
  echo
}

function main() {
    if [ "$#" -eq 0 ]; then
        print_usage
        exit 0;
    fi
    case "$1" in
        "camera_viz" | "fusion_viz" | "perception" | "traffic_light" | "lidar" | "mec" | "rsap" | \
        "om_device_status" | "all" | "stop" | "release"|"ccindex" | "om" | "PTPpartlog" )
            stop_all
            ;;
    esac

    cd /home/airos/os
    source setup.bash

    local cmd="$1"
    GLOBAL_KILL_DAG_NAME="$2"
    shift
    case "${cmd}" in
        camera_viz)
            start_camera_viz
            ;;
        fusion_viz)
            start_fusion_viz
            ;;
        perception)
            start_perception_pipeline
            ;;
        traffic_light)
            start_traffic_light_pipeline
            ;;
        lidar)
            start_perception_lidar
            ;;
        mec)
            start_mec_pipeline
            ;;
        rsap)
            start_rsap_pipeline
            ;;
        om_device_status)
              start_om_device_status_pipeline
              ;;
        ccindex)
              start_ccindex_pipeline
              ;;
        om)
              start_om_pipeline
              ;;
        kill)
              start_kill_dag_pipeline
              ;;
        ps)
              start_ps
              ;;
        all)
            start_all
            ;;
        stop)
            echo "all stop!"
            ;;
        *)
            print_usage
            ;;
    esac
}

main "$@"
